---
application:
  server:
    port: 8080
  db:
    host: "dblocalhost"
    port: 5432
    name: "dbname"
    user: "dbuser"
    password: "dbpassword"
server:
  port: "${application.server.port}"
logging:
  level:
    root: "INFO"
spring:
  jpa:
    show-sql: false
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "create-drop"
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
        implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"
  datasource:
    url: "jdbc:postgresql://${application.db.host}:${application.db.port}/${application.db.name}"
    username: "${application.db.user}"
    password: "${application.db.password}"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://bankwiz-dev.eu.auth0.com/"
          jwk-set-uri: "https://bankwiz-dev.eu.auth0.com/.well-known/jwks.json"