---
application:
  cors-allowed-origins: "http://localhost:5173,http://localhost:4173,http://127.0.0.1:5173,http://127.0.0.1:4173,http://localhost:9680,http://localhost:8280"
spring.devtools.add-properties: true
