---
application:
  cors-allowed-origins: "http://localhost:8080"
  server:
    port: 8080
  db:
    host: "dblocalhost"
    port: 3306
    name: "dbname"
    user: "dbuser"
    password: "dbpassword"
server:
  port: "${application.server.port}"
logging:
  level:
    root: "INFO"
    fr.bankwiz.server.infrastructure.aop:
      SPIInterceptor: "OFF"
      ServiceInterceptor: "INFO"
spring:
  devtools.add-properties: false
  jpa:
    show-sql: false
    database-platform: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: "validate"
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
        implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"
  datasource:
    url: "jdbc:mysql://${application.db.host}:${application.db.port}/${application.db.name}"
    username: "${application.db.user}"
    password: "${application.db.password}"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://bankwiz-dev.eu.auth0.com/"
          jwk-set-uri: "https://bankwiz-dev.eu.auth0.com/.well-known/jwks.json"
