---
application:
  general:
    title: Bankwiz server
    version: 1.0.0-SNAPSHOT
    description: Api server for Bankwiz application
    license: Mozilla Public License Version 2.0
    license-url: https://github.com/jbwittner/bankwiz_server/blob/develop/LICENSE
  web:
    port: 9595
    url: http://localhost:9595
    cors-allowed-origins: ""
  db:
    host: dblocalhost
    port: 5432
    name: dbname
    user: dbuser
    password: dbpassword
  oauth2:
    issuer-uri: https://example.com/
    audience: audience
server:
  port: "${application.web.port}"
logging:
  level:
    root: INFO
    fr.bankwiz.server:
      application.aop: INFO
      domain.service: INFO
      infrastructure:
        spijpa: WARN
        apirest: WARN
spring:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    url: "jdbc:postgresql://${application.db.host}:${application.db.port}/${application.db.name}"
    username: "${application.db.user}"
    password: "${application.db.password}"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${application.oauth2.issuer-uri}"
          jwk-set-uri: "${application.oauth2.issuer-uri}.well-known/jwks.json"
