---
application:
  cors-allowed-origins: http://localhost:5173
  db:
    host: localhost
    port: 54322
    name: bankwiz_db
    user: postgres
    password: l3FL9SN0q7
  oauth2:
    issuer-uri: https://bankwiz-development.eu.auth0.com/
    audience: bankwiz_server
