---
application:
  cors-allowed-origins: http://localhost:5173
  db:
    host: localhost
    port: 5432
    name: bankwiz_db
    user: bankwiz_user
    password: Bankwiz2024
  oauth2:
    issuer-uri: https://bankwiz-development.eu.auth0.com/
    audience: bankwiz_server
