---
application:
  db:
    host: localhost
    port: 3306
    name: bankwiz_db
    user: bankwiz_user
    password: Bankwiz2024
  oauth2:
    issuer-uri: https://bankwiz-dev.eu.auth0.com/
    audience: bankwiz_server
