application:
  server:
    port: 8080
  db-param:
    host: localhost
    port: 8306
    db-name: bankwiz_db
    user: bankwiz_user
    password: BankwizPass2023

server:
  port : ${application.server.port}

spring.jpa.properties.javax.persistence.schema-generation.scripts.action: drop-and-create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target: create.sql
spring.jpa.properties.javax.persistence.schema-generation.scripts.drop-target: drop.sql
spring.jpa.properties.javax.persistence.schema-generation.create-source: metadata
spring.jpa.properties.javax.persistence.schema-generation.drop-source: metadata


auth0:
    audience: Bankwiz_server
spring:
  jpa:
    show-sql: false
    database-platform : org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    url: jdbc:mysql://${application.db-param.host}:${application.db-param.port}/${application.db-param.db-name}
    username: ${application.db-param.user}
    password: ${application.db-param.password}
    driverClassName: com.mysql.cj.jdbc.Driver
  security:
      oauth2:
          resourceserver:
              jwt:
                  issuer-uri: https://bankwiz-dev.eu.auth0.com/
                  jwk-set-uri: https://bankwiz-dev.eu.auth0.com/.well-known/jwks.json