---
volumes:
  db_bankwiz_volume: null
services:
  db:
    image: postgres:17.2
    container_name: bankwiz_database
    ports:
    - 5432:5432
    volumes:
    - db_bankwiz_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bankwiz_db
      POSTGRES_USER: bankwiz_user
      POSTGRES_PASSWORD: Bankwiz2024
      PGDATA: /var/lib/postgresql/data/pgdata
