name: Setup action
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Cache maven
      uses: actions/cache@v3
      env:
        cache-name: cache-maven
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: /home/runner/.m2/settings.xml
        key: maven-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('openapi.yaml') }}-${{ hashFiles('pom.xml') }}-${{ hashFiles('domain/pom.xml') }}-${{ hashFiles('infrastructure/pom.xml') }}
        restore-keys: |
          maven-${{ runner.os }}-build-${{ env.cache-name }}-
          maven-${{ runner.os }}-build-
          maven-${{ runner.os }}-

