name: Pull Request CI
on:
  pull_request:
    branches:
      - develop
env:
  REGISTRY: ghcr.io
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build-install-application:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: Install openapi dependancy
        run: mvn -B clean install -f openapi/pom.xml
      - name: Install java part
        run: mvn -B -DskipTests clean install -Dcheckstyle.skip
  check-google-format:
    runs-on: ubuntu-22.04
    needs:
      - build-install-application
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: Spotless check
        run: mvn -B spotless:check
  checkstyle:
    runs-on: ubuntu-22.04
    needs:
      - build-install-application
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: Checkstyle check
        run: mvn -B checkstyle:checkstyle
  tests_sonar_domain:
    runs-on: ubuntu-22.04
    needs:
      - checkstyle
      - check-google-format
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Test and analyse domain
        working-directory: domain
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
  tests_sonar_infra:
    runs-on: ubuntu-22.04
    needs:
      - checkstyle
      - check-google-format
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Test and analyse infrastructure
        working-directory: infrastructure
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
  build_docker:
    runs-on: ubuntu-22.04
    needs:
      - tests_sonar_infra
      - tests_sonar_domain
    permissions:
      packages: write
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false
          secrets: |
            USER_GITHUB_LOGIN=$GITHUB_ACTOR
            USER_GITHUB_KEY=${{ secrets.GITHUB_TOKEN }}